apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "aws-ecr-credential.cronJob" . }}
  namespace: {{ include "aws-ecr-credential.namespace" . }}
  labels:
{{ include "aws-ecr-credential.labels" . | indent 4 }}
spec:
  schedule: "* */8 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        metadata:
          labels:
{{ include "aws-ecr-credential.podLabels" . | indent 12 }}
        spec:
          serviceAccountName: {{ include "aws-ecr-credential.serviceAccount" . }}
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          containers:
          - name: kubectl
            imagePullPolicy: IfNotPresent
            image: {{ .Values.jobImage }}:{{ .Values.jobImageTag }}
            env:
              - name: ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: {{ include "aws-ecr-credential.secret" . }}
                    key: AWS_ACCESS_KEY_ID
              - name: SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ include "aws-ecr-credential.secret" . }}
                    key: AWS_SECRET_ACCESS_KEY
            command:
            - "/bin/sh"
            - "-c"
            - |
              AWS_ACCOUNT={{ .Values.aws.account }}
              AWS_REGION={{ .Values.aws.region }}
              echo "AWS_ACCOUNT=$AWS_ACCOUNT"
              echo "AWS_REGION=$AWS_REGION"

              aws configure set aws_access_key_id $(ACCESS_KEY_ID)
              aws configure set aws_secret_access_key $(SECRET_ACCESS_KEY)

              DOCKER_REGISTRY_SERVER=https://${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com
              DOCKER_USER=AWS
              DOCKER_PASSWORD=$(aws ecr get-login-password --region ${AWS_REGION})

              echo "DOCKER_REGISTRY_SERVER=$DOCKER_REGISTRY_SERVER"
              echo "DOCKER_USER=$DOCKER_USER"
              echo "DOCKER_PASSWORD=$DOCKER_PASSWORD"a
              {{ range .Values.targetNamespaces }}
                kubectl delete secret --namespace {{ . }} aws-registry --ignore-not-found=true
                kubectl create secret --namespace {{ . }} docker-registry aws-registry \
                --docker-server=$DOCKER_REGISTRY_SERVER \
                --docker-username=$DOCKER_USER \
                --docker-password=$DOCKER_PASSWORD \
                --docker-email=no@email.local
              {{ end }}
              kubectl patch serviceaccount default -p '{"imagePullSecrets":[{"name":"aws-registry"}]}'

